In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
train_df=pd.read_csv('trainp.csv',index_col='Loan_ID')
test_df=pd.read_csv('testp.csv',index_col='Loan_ID')

In [3]:
train_df.head()

Loan_Status  Dependents  ApplicantIncome  CoapplicantIncome  \
Loan_ID                                                                
LP001002           Y         0.0             5849                0.0   
LP001003           N         1.0             4583             1508.0   
LP001005           Y         0.0             3000                0.0   
LP001006           Y         0.0             2583             2358.0   
LP001008           Y         0.0             6000                0.0   

          LoanAmount  Loan_Amount_Term  Credit_History  FamilySize  Ismother  \
Loan_ID                                                                        
LP001002       119.0             360.0             1.0         1.0         0   
LP001003       128.0             360.0             1.0         2.0         0   
LP001005        66.0             360.0             1.0         1.0         0   
LP001006       120.0             360.0             1.0         1.0         0   
LP001008       141.0             360.0             1.0         1.0         0   

          isMale  is_SelfEmployed  isGraduate  Property_Area_Rural  \
Loan_ID                                                              
LP001002       1                0           1                    0   
LP001003       1                0           1                    1   
LP001005       1                1           1                    0   
LP001006       1                0           0                    0   
LP001008       1                0           1                    0   

          Property_Area_Semiurban  Property_Area_Urban  \
Loan_ID                                                  
LP001002                        0                    1   
LP001003                        0                    0   
LP001005                        0                    1   
LP001006                        0                    1   
LP001008                        0                    1   

          Bin_ApplicantIncome_very_low  Bin_ApplicantIncome_low  \
Loan_ID                                                           
LP001002                             0                        0   
LP001003                             0                        0   
LP001005                             0                        1   
LP001006                             1                        0   
LP001008                             0                        0   

          Bin_ApplicantIncome_high  Bin_ApplicantIncome_very_high  isMarried  
Loan_ID                                                                       
LP001002                         0                              1          0  
LP001003                         1                              0          1  
LP001005                         0                              0          1  
LP001006                         0                              0          1  
LP001008                         0                              1          0

In [4]:
train_df['Loan_Status']=np.where(train_df['Loan_Status']=='Y',1,0)

In [5]:
X = train_df.loc[:,'Dependents':].to_numpy().astype('float')
y=train_df['Loan_Status'].ravel()

In [6]:
print(X.shape,y.shape)

(614, 19) (614,)


In [7]:
#train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [8]:
print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(491, 19) (491,)
(123, 19) (123,)


In [9]:
#Average Loan status in train and test
print('Mean Loan approval in train:{0:.3f}'.format(np.mean(y_train)))
print('Mean loan approval in test:{0:.3f}'.format(np.mean(y_test)))

Mean Loan approval in train:0.697
Mean loan approval in test:0.650


In [10]:
from sklearn.dummy import DummyClassifier

In [11]:
#Create model
model_dummy=DummyClassifier(strategy='most_frequent',random_state=42)

In [12]:
#train model
model_dummy.fit(X_train,y_train)
print('Score for baseline model is:{0:.2f}'.format(model_dummy.score(X_test,y_test)))

Score for baseline model is:0.65


In [13]:
#performance metric
from sklearn.metrics import accuracy_score,confusion_matrix, precision_score,recall_score

In [14]:
#Accuracy score
print('Accuracy for baseline model:{0:.2f}'.format(accuracy_score(y_test,model_dummy.predict(X_test))))

Accuracy for baseline model:0.65


In [15]:
#confusion matric
print('Confusion matrix for baseline model:\n {0}'.format(confusion_matrix(y_test,model_dummy.predict(X_test))))

Confusion matrix for baseline model:
 [[ 0 43]
 [ 0 80]]


In [16]:
#precision and recall
print('precision for basel model: {0:.2f}'.format(precision_score(y_test,model_dummy.predict(X_test))))
print('Recall for baseline model: {0:.2f}'.format(recall_score(y_test,model_dummy.predict(X_test))))

precision for basel model: 0.65
Recall for baseline model: 1.00


In [17]:
test_X=test_df.to_numpy().astype('float')
predictions=model_dummy.predict(test_X)

In [18]:
df_submit=pd.DataFrame({'Loan_ID':test_df.index,'Loan_Status':predictions})

In [19]:
df_submit.head()

Loan_ID  Loan_Status
0  LP001015            1
1  LP001022            1
2  LP001031            1
3  LP001035            1
4  LP001051            1

In [20]:
df_submit['Loan_Status']=np.where(df_submit['Loan_Status']==1,'Y','N')

In [21]:
df_submit.head(15)

Loan_ID Loan_Status
0   LP001015           Y
1   LP001022           Y
2   LP001031           Y
3   LP001035           Y
4   LP001051           Y
5   LP001054           Y
6   LP001055           Y
7   LP001056           Y
8   LP001059           Y
9   LP001067           Y
10  LP001078           Y
11  LP001082           Y
12  LP001083           Y
13  LP001094           Y
14  LP001096           Y

In [22]:
df_submit.to_csv('1dummy.csv',index=False)

# LOGISTIC REGRESSION

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:
lr_1=LogisticRegression(random_state=42)

In [25]:
lr_1.fit(X_train,y_train)

/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=42, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [26]:
print('Score of LG model:{0:.2f}'.format(lr_1.score(X_test,y_test)))

Score of LG model:0.80


In [27]:
print('Accuracy for LG ver 1: {0:.2f}'.format(accuracy_score(y_test,lr_1.predict(X_test))))

Accuracy for LG ver 1: 0.80


In [28]:
print('confusion matrix for LG ver1:\n {0}'.format(confusion_matrix(y_test,lr_1.predict(X_test))))
print('precision score for LG ver1: {0:.2f}'.format(precision_score(y_test,lr_1.predict(X_test))))
print('recall for LG ver1: {0:.2f}'.format(recall_score(y_test,lr_1.predict(X_test))))

confusion matrix for LG ver1:
 [[19 24]
 [ 1 79]]
precision score for LG ver1: 0.77
recall for LG ver1: 0.99


In [29]:
lr_1.coef_

array([[ 9.84179812e-02, -1.27851206e-05, -6.17255274e-05,
        -1.69825342e-03, -3.12745989e-03,  2.62590436e+00,
        -2.65002504e-02,  1.95805549e-01, -1.21269699e-01,
         1.79945355e-02,  2.31420099e-01, -3.25646438e-01,
         4.09067855e-01, -2.08339649e-01,  6.11439224e-02,
        -1.45069427e-01, -7.45226541e-02,  3.35299274e-02,
         4.77527542e-01]])

In [30]:
test1_X = test_df.to_numpy().astype('float')
predict1=lr_1.predict(test1_X)

In [31]:
df1=pd.DataFrame({'Loan_ID':test_df.index,'Loan_Status':predict1})

In [32]:
df1.head()

Loan_ID  Loan_Status
0  LP001015            1
1  LP001022            1
2  LP001031            1
3  LP001035            1
4  LP001051            1

In [33]:
df1['Loan_Status']=np.where(df1['Loan_Status']==1,'Y','N')

In [34]:
df1.head()

Loan_ID Loan_Status
0  LP001015           Y
1  LP001022           Y
2  LP001031           Y
3  LP001035           Y
4  LP001051           Y

In [52]:
df1.to_csv('LR_1.csv',index=False)

In [53]:
model_lr=LogisticRegression(random_state=0)

In [54]:
from sklearn.model_selection import GridSearchCV

In [58]:
parameters={'C':[1.0,10.0,50.0,100.0,1000.0],'penalty':['l1','l2']}

In [59]:
clf = GridSearchCV(model_lr,param_grid=parameters,cv=3)

In [60]:
clf.fit(X_train,y_train)

/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/dat

GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'C': [1.0, 10.0, 50.0, 100.0, 1000.0], 'penalty': ['l1', 'l2']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [62]:
clf.best_params_

{'C': 1.0, 'penalty': 'l1'}

In [64]:
print('best score: {0:.2f}'.format(clf.best_score_))

best score: 0.79


In [65]:
print('Score for LG ver 2: {0:.2f}'.format(clf.score(X_test,y_test)))

Score for LG ver 2: 0.80


In [66]:
test2_X=test_df.to_numpy().astype('float')

In [67]:
predict2=clf.predict(test2_X)

In [68]:
df2=pd.DataFrame({'Loan_ID':test_df.index,'Loan_Status':predict2})

In [69]:
df2.head()

Loan_ID  Loan_Status
0  LP001015            1
1  LP001022            1
2  LP001031            1
3  LP001035            1
4  LP001051            1

In [70]:
df2['Loan_Status']=np.where(df2['Loan_Status']==1,'Y','N')

In [71]:
df2.head()

Loan_ID Loan_Status
0  LP001015           Y
1  LP001022           Y
2  LP001031           Y
3  LP001035           Y
4  LP001051           Y

In [72]:
df2.to_csv('03_lr.csv',index=False)

In [74]:
from sklearn.naive_bayes import GaussianNB

In [75]:
classifier=GaussianNB()

In [76]:
classifier.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [78]:
y_pred=classifier.predict(X_test)

In [79]:
print('Accuracy: {0:.2f}'.format(accuracy_score(y_test,y_pred)))
print('precision: {0:.2f}'.format(precision_score(y_test,y_pred)))
print('Recall: {0:.2f}'.format(recall_score(y_test,y_pred)))
print('confusion matrix: \n {0}'.format(confusion_matrix(y_test,y_pred)))

Accuracy: 0.79
precision: 0.76
Recall: 0.97
confusion matrix: 
 [[19 24]
 [ 2 78]]


In [87]:
test3=test_df.to_numpy().astype('float')

In [88]:
predict3=classifier.predict(test3)

In [89]:
df3=pd.DataFrame({'Loan_ID':test_df.index,'Loan_Status':predict3})
df3.head()

Loan_ID  Loan_Status
0  LP001015            1
1  LP001022            1
2  LP001031            1
3  LP001035            1
4  LP001051            1

In [90]:
df3['Loan_Status']=np.where(df3['Loan_Status']==1,'Y','N')
df3.head()

Loan_ID Loan_Status
0  LP001015           Y
1  LP001022           Y
2  LP001031           Y
3  LP001035           Y
4  LP001051           Y

In [91]:
df3.to_csv('03_GNB.csv',index=False)

In [92]:
from sklearn.ensemble import RandomForestClassifier

In [94]:
clf1=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)

In [95]:
clf1.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [96]:
y1_pred=clf1.predict(X_test)

In [97]:
print('Accuracy:',accuracy_score(y_test,y1_pred))
print('Precision:', precision_score(y_test,y1_pred))
print('Recall:',recall_score(y_test,y1_pred))
print('confusion matrix:\n',confusion_matrix(y_test,y1_pred))

Accuracy: 0.7560975609756098
Precision: 0.7604166666666666
Recall: 0.9125
confusion matrix:
 [[20 23]
 [ 7 73]]


In [98]:
test4=test_df.to_numpy().astype('float')

In [99]:
predict4=clf1.predict(test4)

In [100]:
df4=pd.DataFrame({'Loan_ID':test_df.index,'Loan_Status':predict4})
df4.head()

Loan_ID  Loan_Status
0  LP001015            1
1  LP001022            1
2  LP001031            1
3  LP001035            1
4  LP001051            0

In [101]:
df4['Loan_Status']=np.where(df4['Loan_Status']==1,'Y','N')
df4.head()

Loan_ID Loan_Status
0  LP001015           Y
1  LP001022           Y
2  LP001031           Y
3  LP001035           Y
4  LP001051           N

In [102]:
df4.to_csv('04_Rf.csv',index=False)

In [103]:
train_df.columns

Index(['Loan_Status', 'Dependents', 'ApplicantIncome', 'CoapplicantIncome',
       'LoanAmount', 'Loan_Amount_Term', 'Credit_History', 'FamilySize',
       'Ismother', 'isMale', 'is_SelfEmployed', 'isGraduate',
       'Property_Area_Rural', 'Property_Area_Semiurban', 'Property_Area_Urban',
       'Bin_ApplicantIncome_very_low', 'Bin_ApplicantIncome_low',
       'Bin_ApplicantIncome_high', 'Bin_ApplicantIncome_very_high',
       'isMarried'],
      dtype='object')

In [105]:
X=train_df[['ApplicantIncome','CoapplicantIncome','LoanAmount',
      'Credit_History','FamilySize','isMale','is_SelfEmployed','isGraduate']]
y=train_df['Loan_Status']

In [107]:
X=X.to_numpy().astype('float')
y=y.ravel()

In [108]:
print(X.shape,y.shape)

(614, 8) (614,)


In [109]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [110]:
print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(429, 8) (429,)
(185, 8) (185,)


In [111]:
print(f'mean loan approval in train: {np.mean(y_train)}')
print(f'mean loan approval in test: {np.mean(y_test)}')

mean loan approval in train: 0.6713286713286714
mean loan approval in test: 0.7243243243243244


In [112]:
dummy=DummyClassifier(strategy='most_frequent',random_state=0)

In [113]:
dummy.fit(X_train,y_train)

DummyClassifier(constant=None, random_state=0, strategy='most_frequent')

In [114]:
print('New baseline model:{0:.3f}'.format(dummy.score(X_test,y_test)))

New baseline model:0.724


In [115]:
dum_p=dummy.predict(X_test)

In [117]:
print('Accuracy: ',accuracy_score(y_test,dum_p))
print('precision: ',precision_score(y_test,dum_p))
print('recall: ',recall_score(y_test,dum_p))
print('confusion matrix:\n',confusion_matrix(y_test,dum_p))

Accuracy:  0.7243243243243244
precision:  0.7243243243243244
recall:  1.0
confusion matrix:
 [[  0  51]
 [  0 134]]


In [118]:
class1=GaussianNB()

In [119]:
class1.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [120]:
y_pred=class1.predict(X_test)
print('Accuracy:',accuracy_score(y_test,y_pred))
print('precision:',precision_score(y_test,y_pred))
print('Recall:',recall_score(y_test,y_pred))
print('Confusion matrix:\n' ,confusion_matrix(y_test,y_pred))

Accuracy: 0.8216216216216217
precision: 0.821656050955414
Recall: 0.9626865671641791
Confusion matrix:
 [[ 23  28]
 [  5 129]]


In [127]:
testX=test_df[['ApplicantIncome','CoapplicantIncome','LoanAmount','Credit_History','FamilySize','isMale','is_SelfEmployed','isGraduate']].to_numpy().astype('float')

In [128]:
predict=class1.predict(testX)

In [129]:
df5=pd.DataFrame({'Loan_ID':test_df.index,'Loan_Status':predict})
df5.head()

Loan_ID  Loan_Status
0  LP001015            1
1  LP001022            1
2  LP001031            1
3  LP001035            1
4  LP001051            1

In [130]:
df5['Loan_Status'] = np.where(df5['Loan_Status'] == 1,'Y','N')
df5.head()

Loan_ID Loan_Status
0  LP001015           Y
1  LP001022           Y
2  LP001031           Y
3  LP001035           Y
4  LP001051           Y

In [131]:
df5.to_csv('05_P.csv',index=False)

In [133]:
lr_2=LogisticRegression(random_state=0)

In [134]:
lr_2.fit(X_train,y_train)

/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [135]:
print('Score: ',lr_2.score(X_test,y_test))

Score:  0.8324324324324325


In [136]:
n_yp = lr_2.predict(X_test)

In [139]:
print('Accuracy:',accuracy_score(y_test,n_yp))
print('precision:',precision_score(y_test,n_yp))
print('recall:',recall_score(y_test,n_yp))
print('confusion:\n',confusion_matrix(y_test,n_yp))

Accuracy: 0.8324324324324325
precision: 0.8238993710691824
recall: 0.9776119402985075
confusion:
 [[ 23  28]
 [  3 131]]


In [140]:
predictn=lr_2.predict(testX)

In [141]:
df6=pd.DataFrame({'Loan_ID':test_df.index,'Loan_Status':predictn})
df6.head()

Loan_ID  Loan_Status
0  LP001015            1
1  LP001022            1
2  LP001031            1
3  LP001035            1
4  LP001051            1

In [142]:
df6['Loan_Status'] = np.where(df6['Loan_Status'] == 1,'Y','N')
df6.head()

Loan_ID Loan_Status
0  LP001015           Y
1  LP001022           Y
2  LP001031           Y
3  LP001035           Y
4  LP001051           Y

In [143]:
df6.to_csv('06_P.csv',index=False)